name: BrewMate
options:
  bundleIdPrefix: com.multimodalsolutions
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    PRODUCT_NAME: BrewMate

targets:
  BrewMate:
    type: application
    platform: macOS
    sources:
      - path: BrewMate
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.multimodalsolutions.brewmate
        INFOPLIST_FILE: BrewMate/Info.plist
        CODE_SIGN_ENTITLEMENTS: BrewMate/BrewMate.entitlements
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    entitlements:
      path: BrewMate/BrewMate.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.cs.allow-unsigned-executable-memory: true

schemes:
  BrewMate:
    build:
      targets:
        BrewMate: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
