name: Taphouse
options:
  bundleIdPrefix: com.multimodalsolutions
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    PRODUCT_NAME: Taphouse
    OTHER_CODE_SIGN_FLAGS: "--timestamp --options=runtime"

targets:
  Taphouse:
    type: application
    platform: macOS
    sources:
      - path: Taphouse
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Sparkle
        product: Sparkle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.multimodalsolutions.taphouse
        INFOPLIST_FILE: Taphouse/Info.plist
        CODE_SIGN_ENTITLEMENTS: Taphouse/Taphouse.entitlements
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    entitlements:
      path: Taphouse/Taphouse.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.cs.allow-unsigned-executable-memory: true

schemes:
  Taphouse:
    build:
      targets:
        Taphouse: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
